name: Airflow CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t airflow-dag:${{ github.sha }} .
          docker tag airflow-dag:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/airflow-dag:latest

      # Push image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/airflow-dag:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/airflow-dag:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2



